name: Run tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"


jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install app requirements
        run: pip install -r requirements.txt
      - name: Install test requirements
        run: pip install -r requirements-test.txt
      - name: Run PyLint tests
        run: pylint src/*.py
      - name: Run Bandit tests
        run: bandit src/*.py --skip B101
      - name: Run Unit tests
        run: pytest src/test_unit.py
      - name: Generate SSL certificates
        run: ./make_cert.sh
      - name: Bring App Up
        run: docker-compose up -d
      - name: Wait for App to be Up
        run: ./wait_for_https.sh 60
      - name: Run System Tests
        run: pytest src/test_system.py
